### PR TITLE
Optimized global script, and changed main menu.

### PR DESCRIPTION
**Pull request by pricklee**
This PR changes many scripts and optimizes the visualizer and some global scripts, and also adds a new hit type: Numbers.

### CODE REVIEW

**Review by dimitrije-k — APPROVED** [review]
Good stuff

**Review by dimitrije-k — APPROVED** [review]
Approved hopefully

**Review by dimitrije-k — APPROVED** [review]
?????

**Review by pricklee — COMMENTED** [review]
alr

**Pull request merged**
